// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiy2K9cLchS22AxJ8fmc7U4Nh9VCdmyEM',
    appId: '1:167764670972:web:5f5760de3c4d690af95a79',
    messagingSenderId: '167764670972',
    projectId: 'sigin-test-d9b86',
    authDomain: 'sigin-test-d9b86.firebaseapp.com',
    storageBucket: 'sigin-test-d9b86.appspot.com',
    measurementId: 'G-64WEBJ3L7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt2NGsvJK_EvIvTY8CH4o5AajvHwGxlyA',
    appId: '1:167764670972:android:0056d4f86ec14695f95a79',
    messagingSenderId: '167764670972',
    projectId: 'sigin-test-d9b86',
    storageBucket: 'sigin-test-d9b86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwP-ALopI89DnsdgOmz9CQ590whAbTGdA',
    appId: '1:167764670972:ios:e0146e120f296851f95a79',
    messagingSenderId: '167764670972',
    projectId: 'sigin-test-d9b86',
    storageBucket: 'sigin-test-d9b86.appspot.com',
    androidClientId: '167764670972-24vkb60v2lfskne6avu6icaqsb04gct7.apps.googleusercontent.com',
    iosClientId: '167764670972-pvbnvjfa2a0m50oag58c0697af3ngsud.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBinAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwP-ALopI89DnsdgOmz9CQ590whAbTGdA',
    appId: '1:167764670972:ios:081fddb75186287df95a79',
    messagingSenderId: '167764670972',
    projectId: 'sigin-test-d9b86',
    storageBucket: 'sigin-test-d9b86.appspot.com',
    androidClientId: '167764670972-24vkb60v2lfskne6avu6icaqsb04gct7.apps.googleusercontent.com',
    iosClientId: '167764670972-idbt4tu0lt1ga165166cfoceruiu1l6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBinAlert.RunnerTests',
  );
}
